# Generated by Django 2.2 on 2022-04-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingredients', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=200)),
                ('image', models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fplate&psig=AOvVaw0MX3G1sCt7ND-FBIXv69ZM&ust=1650592695338000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLj3mYuHpPcCFQAAAAAdAAAAABAD', max_length=500)),
            ],
        ),
    ]
