# Generated by Django 2.2 on 2022-04-21 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howeydoin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Funsplash.com%2Fs%2Fphotos%2Fplate&psig=AOvVaw0MX3G1sCt7ND-FBIXv69ZM&ust=1650592695338000&source=images&cd=vfe&ved=0CAwQjRxqFwoTCLj3mYuHpPcCFQAAAAAdAAAAABAD', upload_to='pictures'),
        ),
    ]
