# Generated by Django 2.2 on 2022-04-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('howeydoin', '0002_auto_20220420_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.CharField(max_length=2000),
        ),
    ]
